CC = gcc
CFLAGS = -Werror -Wall

#g++ -I /usr/include/boost_1_79_0/ -I /usr/include/boost_1_79_0/boost/ -L /usr/include/boost_1_79_0/ -lpthread -lcrypto -lssl TraderWebsockets.cpp -o TraderWebsockets.outmake

gcc -Werror -Wfatal-errors -pedantic-errors -Wall main.c Container.o

gcc -c -Werror -Wfatal-errors -pedantic-errors -Wall Container.c -o Container.o